# Generated by Django 4.2 on 2023-09-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booked",
            name="Booked_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
