# Generated by Django 4.2 on 2023-10-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_alter_booked_booked_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="description",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
