# Generated by Django 4.2 on 2023-10-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_images_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="images",
            name="title",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
