# Generated by Django 4.2 on 2023-10-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_images_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="dress_size",
            field=models.JSONField(default=list),
        ),
    ]
