# Generated by Django 4.2 on 2023-10-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_alter_images_dress_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="booked",
            name="size",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
