# Generated by Django 5.2 on 2025-07-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_rename_images_dress_cart"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Dress",
            new_name="Dresses",
        ),
    ]
