# Generated by Django 5.2 on 2025-08-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_rename_dress_dresses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dresses",
            name="dress_for",
        ),
        migrations.RemoveField(
            model_name="dresses",
            name="type",
        ),
        migrations.AddField(
            model_name="dresses",
            name="dress_type",
            field=models.CharField(
                choices=[
                    ("traditional", "Traditional"),
                    ("party", "Party Wear"),
                    ("daily", "Daily Wear"),
                    ("wedding", "Wedding"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dresses",
            name="main_category",
            field=models.CharField(
                choices=[
                    ("women", "Women"),
                    ("men", "Men"),
                    ("boykid", "Boy Kid"),
                    ("girlkid", "Girl Kid"),
                    ("homeacc", "Home Accessories"),
                    ("gifts", "Gifts"),
                    ("jewellery", "Jewellery"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dresses",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="dresses",
            name="dressid",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="dresses",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
