# Generated by Django 5.2 on 2025-08-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_remove_dresses_dress_for_remove_dresses_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dresses",
            name="description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="dresses",
            name="dressid",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
